In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 15)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
arr[1]

2

In [4]:
arr[3:7]

array([4, 5, 6, 7])

In [5]:
arr[:5]

array([1, 2, 3, 4, 5])

In [6]:
arr[5:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
arr[0:6] = 100 # Python list không thể làm được điều này
arr

array([100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,  13,
        14])

In [8]:
arr = np.arange(1, 15)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
slice_arr = arr[8:]
slice_arr 

array([ 9, 10, 11, 12, 13, 14])

In [10]:
slice_arr[:] = 99 # Chọn tất cả index trong mảng
slice_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
arr # slice_arr thay đổi giá trị nên arr cũng bị thay đổi theo

array([ 1,  2,  3,  4,  5,  6,  7,  8, 99, 99, 99, 99, 99, 99])

In [12]:
arr_copy = arr.copy() # Sử dụng copy để khi thay đổi arr_copy cũng không thay đổi mảng gốc arr
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8, 99, 99, 99, 99, 99, 99])

In [13]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100])

In [14]:
arr # Không bị thay đổi

array([ 1,  2,  3,  4,  5,  6,  7,  8, 99, 99, 99, 99, 99, 99])

In [15]:
arr_2d = np.random.randint(1, 50, (5, 7))
arr_2d

array([[26, 15, 33, 23, 10, 30, 25],
       [13, 32, 40, 47, 33, 39, 14],
       [13,  7, 20, 29, 43, 48, 43],
       [11, 10,  5, 16, 32,  9, 14],
       [36, 38,  1, 21, 20,  8, 15]])

In [16]:
arr_2d[0]

array([26, 15, 33, 23, 10, 30, 25])

In [17]:
arr_2d[-1]

array([36, 38,  1, 21, 20,  8, 15])

In [18]:
arr_2d[1, 1] # arr_2d[1][1]

32

In [19]:
arr_2d[-1, -2]

8

In [20]:
arr_2d[:2, :4]

array([[26, 15, 33, 23],
       [13, 32, 40, 47]])

In [21]:
arr_2d[-2:, -3:]

array([[32,  9, 14],
       [20,  8, 15]])

In [22]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
bool_arr = arr > 4
bool_arr # Có thể dùng để filter

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [24]:
arr[bool_arr] # Lọc những giá trị lớn hơn 4 trong arr

array([ 5,  6,  7,  8,  9, 10])

In [25]:
arr[arr <= 4] # Lọc những giá trị nhỏ hơn hoặc bằng 4 trong arr

array([1, 2, 3, 4])